baseURL = 'https://rafaelmfonseca.github.io/'
languageCode = 'en-us'
title = 'Rafael Moreira Fonseca'
theme = 'paper'
disqusShortname = 'rafaelmfonseca'
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true