baseURL = 'https://rafaelmfonseca.github.io/blog/'
author = 'Rafael Moreira Fonseca'
copyright = "Copyright © 2021-2023, Rafael Moreira Fonseca; all rights reserved."
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

title = 'Rafael Moreira Fonseca'
theme = 'hugo-paper'

disqusShortname = 'rafaelmfonseca'
rssLimit = 10
enableEmoji = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params]
    color = 'linen'
    github = 'RafaelMFonseca'
    linkedin = 'rafael-moreira-fonseca'
    customCSS = ["css/disqusfix.css"]